In [185]:
from plyfile import PlyData, PlyElement
import numpy as np

In [186]:
plydata = PlyData.read('tex.ply')

In [187]:
len(plydata)

2

In [188]:
print(plydata)

ply
format ascii 1.0
comment zipper output
element vertex 4
property float x
property float y
property float z
element face 4
property list uchar int vertex_indices
end_header


In [189]:
plydata['vertex']

PlyElement('vertex', (PlyProperty('x', 'float'), PlyProperty('y', 'float'), PlyProperty('z', 'float')), count=4, comments=[])

In [190]:
plydata['vertex'][1]

(0., 1., 0.)

In [191]:
plydata['face'][0][0]

array([0, 1, 2], dtype=int32)

In [192]:
count = 0
for x in plydata['vertex']:
#     print(x[0], x[1], x[2])
#     print(str([x[0], x[1], x[2]]))
    count += 1

In [193]:
count

4

In [194]:
#calculate and store area-weighted vertex normals for future use#
vertex_normals = np.zeros((count, 3))
for x in plydata['face']:
    #get indexs of vertices in the face #
    index = x[0]
    
    #get corresponding vertices# 
    point_a = plydata['vertex'][index[0]]
    point_b = plydata['vertex'][index[1]]
    point_c = plydata['vertex'][index[2]]
    
    #use np to reconstruct to eliminate extra properties rather than xyz and vector calculation#
    t_point_a = np.array([point_a[0], point_a[1], point_a[2]])
    t_point_b = np.array([point_b[0], point_b[1], point_b[2]])
    t_point_c = np.array([point_c[0], point_c[1], point_c[2]])
    
    #construct vectors in the face#
    v1 = t_point_b - t_point_a
    v2 = t_point_c - t_point_a
    
    #calculate normal and then normalize#
    normal = np.cross(v1, v2)
    normal = normal / (np.linalg.norm(normal))
    print(normal)
    
    #add normals to relavant vertex indexs 
    vertex_normals[index[0]] += normal
    vertex_normals[index[1]] += normal
    vertex_normals[index[2]] += normal

[0. 0. 1.]
[ 0.57735026 -0.57735026  0.57735026]
[0.57735026 0.57735026 0.57735026]
[-1.  0.  0.]


In [195]:
print(vertex_normals)

[[ 1.15470052  0.          2.15470052]
 [-0.42264974  0.57735026  1.57735026]
 [-0.42264974 -0.57735026  1.57735026]
 [ 0.15470052  0.          1.15470052]]


In [196]:
normalized_vector_normals = []
for x in vertex_normals:
    if (np.linalg.norm(x) > 0.0):
        x = x / (np.linalg.norm(x))
    normalized_vector_normals.append(x)

In [197]:
print(normalized_vector_normals)

[array([0.47234749, 0.        , 0.88141242]), array([-0.24401694,  0.33333333,  0.9106836 ]), array([-0.24401694, -0.33333333,  0.9106836 ]), array([0.13278816, 0.        , 0.99114444])]


In [198]:
f = open("tex.xyz", "w")

In [199]:
f.write(str(count) + "\n")

2

In [200]:
index = 0
while (index < count):
    f.write(str(plydata['vertex'][index][0]) + " ")
    f.write(str(plydata['vertex'][index][1]) + " ")
    f.write(str(plydata['vertex'][index][2]) + " ")
    f.write(str(normalized_vector_normals[index][0]) + " ")
    f.write(str(normalized_vector_normals[index][1]) + " ")
    f.write(str(normalized_vector_normals[index][2]) + "\n")
    index += 1